//
//  Recommendation.swift
//  bilu
//

import Foundation

struct PlaceReview: Codable {
    let authorName: String
    let rating: Int
    let text: String
    let relativeTimeDescription: String
}

struct Recommendation: Codable {
    let name: String
    let dish: String
    let image: String?
    let explanation: String
    let mapsUrl: String
    let latitude: Double?
    let longitude: Double?
    // Enriched from Google Places
    let rating: Double?
    let reviewCount: Int?
    let photos: [String]?
    let reviews: [PlaceReview]?
    let address: String?
    let phone: String?
    let website: String?
    let isOpen: Bool?
    // Generated by Gemini
    let tips: [String]?

    init(
        name: String, dish: String, image: String?, explanation: String,
        mapsUrl: String, latitude: Double? = nil, longitude: Double? = nil,
        rating: Double? = nil, reviewCount: Int? = nil, photos: [String]? = nil,
        reviews: [PlaceReview]? = nil, address: String? = nil, phone: String? = nil,
        website: String? = nil, isOpen: Bool? = nil, tips: [String]? = nil
    ) {
        self.name = name; self.dish = dish; self.image = image
        self.explanation = explanation; self.mapsUrl = mapsUrl
        self.latitude = latitude; self.longitude = longitude
        self.rating = rating; self.reviewCount = reviewCount; self.photos = photos
        self.reviews = reviews; self.address = address; self.phone = phone
        self.website = website; self.isOpen = isOpen; self.tips = tips
    }
}

extension Recommendation: Identifiable {
    var id: String { mapsUrl }
}

struct VibeResult: Codable {
    let recommendations: [Recommendation]
    let groundingPlaces: [GroundingPlace]?
}

struct GroundingPlace: Codable {
    let placeId: String
    let title: String
    let uri: String
}
